USE one;
CREATE TABLE one.o_d_show (
  SHOW_ID int(11) NOT NULL AUTO_INCREMENT,
  NUMBER int(11) NOT NULL,
  TIME float NOT NULL,
  LATITUDE float NOT NULL,
  LONGTITUDE float NOT NULL,
  DEMO_ID int(11) NOT NULL,
  PRIMARY KEY (SHOW_ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 1827
AVG_ROW_LENGTH = 67
CHARACTER SET utf8
COLLATE utf8_general_ci;