USE one;
CREATE TABLE one.o_doctor (
  IMEI int(11) NOT NULL,
  DOCTOR_ID int(11) NOT NULL,
  SNCHAR char(1) DEFAULT NULL,
  SECOND_NAME varchar(255) DEFAULT NULL,
  FIRST_NAME varchar(255) DEFAULT NULL,
  THIRD_NAME varchar(255) DEFAULT NULL,
  HOSPITAL_ID int(11) DEFAULT NULL,
  TEL varchar(50) DEFAULT NULL,
  EMAIL varchar(50) DEFAULT NULL,
  POSITION_ varchar(50) DEFAULT NULL,
  SPECIALITY varchar(50) DEFAULT NULL,
  FILE_ID int(11) NOT NULL,
  PRIMARY KEY (IMEI, DOCTOR_ID),
  CONSTRAINT FK_o_doctor_o_upload_files_ID FOREIGN KEY (FILE_ID)
  REFERENCES one.o_upload_files (ID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = 'Доктора и врачи';