USE one;
CREATE TABLE one.o_upload_files (
  ID int(11) NOT NULL AUTO_INCREMENT,
  IMEI int(11) NOT NULL,
  TYPE varchar(255) NOT NULL,
  HASH varchar(32) NOT NULL,
  TIMESTAMP timestamp DEFAULT CURRENT_TIMESTAMP,
  FILE mediumblob NOT NULL,
  ERR text DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 42
AVG_ROW_LENGTH = 1589248
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = 'Загруженные файлы на сервер';