USE one;
CREATE TABLE one.o_user (
  USER_ID int(11) NOT NULL AUTO_INCREMENT,
  SECOND_NAME varchar(50) DEFAULT NULL,
  FIRST_NAME varchar(50) DEFAULT NULL,
  THIRD_NAME varchar(50) DEFAULT NULL,
  IMEI varchar(15) DEFAULT NULL,
  LOGIN varchar(255) NOT NULL,
  BIRTH_DATE date NOT NULL,
  MANAGER_ID int(11) DEFAULT NULL,
  PRIMARY KEY (USER_ID),
  INDEX IDX_o_user_MANAGER_ID (MANAGER_ID),
  UNIQUE INDEX UK_o_users_LOGIN (LOGIN)
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci;